#!/bin/bash

#parsed by qsub
#run

module load intel-suite
module load anaconda3/personal

mu_id=$PBS_ARRAY_INDEX

#base=$HOME/cubes/metallicity
#base=$HOME/cubes
base=/rds/general/user/rtagirov/ephemeral/cubes

dir=$base/$run/$mu_id

tmp=$TMPDIR

ln -s $dir/* $tmp

#/usr/bin/time -v $tmp/cpline.exe > $tmp/cpline.log 2>&1
./cpline.exe > cpline.log 2>&1

python extract_slices.py atlas noitrp $mu_id
#python extract_slices.py nessy
#python extract_atms.py nessy 10
#python extract_atms.py atlas 10

rsync -aq --no-links $tmp/ $dir/

module purge
