#!/bin/bash

conda_init()
{
__conda_setup="$('/cm/shared/apps/python/intelpython37/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/cm/shared/apps/python/intelpython37/etc/profile.d/conda.sh" ]; then
        . "/cm/shared/apps/python/intelpython37/etc/profile.d/conda.sh"
    else
        export PATH="/cm/shared/apps/python/intelpython37/bin:$PATH"
    fi
fi
unset __conda_setup
}

#parsed by qsub
#host
#run

if [ $host == imperial ]; then

    module load intel-suite
    module load anaconda3/personal

    mu_id=$PBS_ARRAY_INDEX

#   base=$HOME/cubes/metallicity
#   base=$HOME/cubes
    base=/rds/general/user/rtagirov/ephemeral/cubes

    dir=$base/$run/$mu_id

    tmp=$TMPDIR

    ln -s $dir/* $tmp

elif [ $host == dirac_leicester ]; then

    module load intel/compilers/17.0.4
    module load python/intel/3.7

    conda_init

#    conda init bash

#    bash

    conda activate py3.8.3

    mu_id=$PBS_ARRAYID

#   base=$HOME/cubes/metallicity
#   base=$HOME/cubes
#    base=/rds/general/user/rtagirov/ephemeral/cubes
    base=/scratch/dp100/dc-tagi1/cubes

    dir=$base/$run/$mu_id

    tmp=$TMPDIR

    ln -s $dir/* $tmp

    cd $tmp

elif [ $host == dirac_cambridge ]; then

    mu_id=$SLURM_ARRAY_TASK_ID

#   base=$HOME/cubes/metallicity
#   base=$HOME/cubes
#   base=/rds/general/user/rtagirov/ephemeral/cubes
    base=${HOME}/rds/rds-dirac-dp100-n0fcCTMMDq4/dc-tagi1/cubes

    dir=$base/$run/$mu_id

    cd $dir

fi

#/usr/bin/time -v $tmp/cpline.exe > $tmp/cpline.log 2>&1
./cpline.exe > cpline.log 2>&1

#python extract_slices.py atlas noitrp $mu_id
python extract_slices.py nessy itrp
#python extract_atms.py nessy 10
#python extract_atms.py atlas 10

if [[ $host == imperial ]] || [[ $host == dirac_leicester ]]; then

    rsync -aq --no-links $tmp/ $dir/

    module purge

fi
