#!/bin/bash

#parsed by qsub
#host
#run

if [ $host == imperial ]; then

    module load intel-suite
    module load anaconda3/personal

    mu_id=$PBS_ARRAY_INDEX

#   base=$HOME/cubes/metallicity
#   base=$HOME/cubes
    base=/rds/general/user/rtagirov/ephemeral/cubes

    dir=$base/$run/$mu_id

    tmp=$TMPDIR

    ln -s $dir/* $tmp

elif [ $host == dirac_cambridge ]; then

    mu_id=$SLURM_ARRAY_TASK_ID

#   base=$HOME/cubes/metallicity
#   base=$HOME/cubes
#   base=/rds/general/user/rtagirov/ephemeral/cubes
    base=${HOME}/rds/rds-dirac-dp100-n0fcCTMMDq4/dc-tagi1/cubes

    dir=$base/$run/$mu_id

    cd $dir

fi

#/usr/bin/time -v $tmp/cpline.exe > $tmp/cpline.log 2>&1
./cpline.exe > cpline.log 2>&1

#python extract_slices.py atlas noitrp $mu_id
python extract_slices.py nessy itrp
#python extract_atms.py nessy 10
#python extract_atms.py atlas 10

if [ $host == imperial ]; then

    rsync -aq --no-links $tmp/ $dir/

    module purge

fi
