#!/bin/bash

#submit_mu metallicity/mh0-300/308000
#submit_mu metallicity/mh0-300-no-ext/308000

#submit_mu metallicity/mh0-hyd/230777
#submit_mu metallicity/mh0-hyd/233100
#submit_mu metallicity/mh0-hyd/235427

#submit_mu metallicity/mh0-ssd/237495
#submit_mu metallicity/mh0-ssd/244258
#submit_mu metallicity/mh0-ssd/251568

#submit_mu metallicity/mh1-300/182000

#submit_mu metallicity/mh1-hyd/004661
#submit_mu metallicity/mh1-hyd/007049  
#submit_mu metallicity/mh1-hyd/009383

#submit_mu metallicity/mh1-ssd/536452
#submit_mu metallicity/mh1-ssd/542081
#submit_mu metallicity/mh1-ssd/547390

#-------------------------------------------

#submit_mu matthias_ext/hydro/123000
#submit_mu matthias_ext/ssd/186000
#submit_mu matthias_ext/300G/118000

#-------------------------------------------

#submit_mu metallicity/mh5-hyd/210447
#submit_mu metallicity/mh5-hyd/230001
#submit_mu metallicity/mh5-hyd/256938

#submit_mu metallicity/mh5-ssd/716840
#submit_mu metallicity/mh5-ssd/751264
#submit_mu metallicity/mh5-ssd/791247

#submit_mu metallicity/mh5-300/635000
#submit_mu metallicity/mh5-300/637500
#submit_mu metallicity/mh5-300/640000

#-------------------------------------------

#submit_mu veronika/G2V/hydro/214519
submit_mu veronika/G2V/ssd/222809
#submit_mu veronika/G2V/300G/627321
