#!/bin/bash

if [ $# != 1 ]; then

    echo "nessy or atlas?"

    exit 1

fi

form=$1

if [ $form != nessy ] && [ $form != atlas ]; then

    echo "Format is not recognized. Abort."

    exit 1

fi

#dirs=$(seq 1 9)
dirs='1 2 4 6 8'

for d in $dirs; do

    cd $d

    rm -f nohup.out

    nohup python extract_slices.py $form &

    cd ..

done

wait

mkdir -p atms/$form

rm -rf ./atms/$form/*

for d in $dirs; do

    mv ./$d/atms/$form ./atms/$form/$d

done
