#!/bin/bash

function move_output()
{

nc1=$(ls *_onTau.*.nc taugrid.*.nc)

nc2=$(ls P.*.nc T.*.nc rho.*.nc tauross.*.nc tau200.*.nc)

hd=$(ls Header_*)

if [ "$1" != 0 ]; then

    for f in $nc1; do

        mv $f $f.$1

        mv $f.$1 -t ./nc/

    done

    rm $nc2

elif [ "$1" == 0 ]; then

    for f in $nc1; do

        mv $f $f.$1

        mv $f.$1 -t ./nc/

    done

    for f in $nc2; do

        mv $f -t ./nc/

    done

fi

for f in $hd; do

    mv $f $f.$1

    mv $f.$1 -t ./header/

done

mv tau.out tau.out.$1
mv tau.log tau.log.$1

mv tau.out.$1 -t ./header/
mv tau.log.$1 -t ./header/

}

if [ ! $1 ]; then 

    echo "The script expects an argument. Abort."

    exit 0

fi

#step=7.562792000650358E-002
step=0.08

#exit 0

#top='-9.5 -9.0 -8.5 -8.0 -7.5 -7.0'
top='-7.0 -7.5 -8.0 -8.5 -9.0 -9.5 -10.0'
#top='-7.0'
#bot='1.4 1.2 1.0'

declare -i j

j=0

for l in $top; do

    sed -i '$ d' INPUT

    echo $l $step 2.0 >> INPUT

    ./cpline.exe

    move_output $j

    j=$j+1

done

#for u in $bot; do

#    sed -i '$ d' INPUT

#    echo -10.0 $step $u >> INPUT

#    ./cpline.exe

#    move_output $j

#    j=$j+1

#done

#exit 0

#sed -i '$ d' INPUT

#echo -10.0 $step 2.0 >> INPUT

#./cpline.exe

#move_output $j

python extract_atms_netcdf.py $1
