#!/bin/bash

scr=${HOME}/cubes_pipline/scr
inp=${HOME}/cubes_pipline/inp
exe=${HOME}/cubes_pipline/src/cpline.exe

#cubes=${HOME}/cubes/metallicity
#cubes=/rds/general/user/rtagirov/ephemeral/cubes/metallicity
#cubes=/rds/general/user/rtagirov/ephemeral/cubes/veronika/G2V
cubes=/scratch/dp100/dc-tagi1/cubes/veronika/G2V
#cubes=${HOME}/cubes/matthias
#cubes=${HOME}/cubes/matthias_ext
#cubes=${HOME}/cubes/veronika/G2V
#cubes=${HOME}/rds/rds-dirac-dp100-n0fcCTMMDq4/dc-tagi1/cubes/matthias
#cubes=${HOME}/rds/rds-dirac-dp100-n0fcCTMMDq4/dc-tagi1/cubes/veronika/G2V

declare -i mu_id

#dirs=$(ls -d mh5*)
#dirs=mh0-300-no-ext
#dirs=mh1-hyd
#dirs='300G hydro ssd'
dirs='300G ssd'
#dirs='hydro'

#mu_ids='1 3 5 7 9'
mu_ids='2 4 6 8 10'
#mu_ids='2 10'
#mu_ids='2'
#mu_ids='10'
#mu_ids='1 2 3 4 5 6 7 8 9 10'
#mu_ids='4'

#mu=(1.0 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2)
mu=(0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0)
#mu=(0.2 0.4 0.6 0.8 1.0)
#mu=(0.4)

for d in $dirs; do

    echo Creating mu dirs for ${d}...

    cd $d

    nums=$(ls -d *)

    for n in $nums; do

        for mu_id in $mu_ids; do

            dest=$n/$mu_id

            rm -rf $dest

#            continue

            mkdir -p $dest

            pdir=$(pwd)

            cd $dest

            ln -s $cubes/$d/$n/*.bin     ./
            ln -s $cubes/$d/$n/dims.inp  ./

            cp $inp/INPUT_rot_itrp ./INPUT
#            cp $inp/INPUT_rot_itrp_matthias_pivot ./INPUT
#            cp $inp/INPUT_rot ./INPUT

            cp $inp/ross_table.dat    ./
            cp $inp/kappa_table.dat   ./

            ln -s $scr/extract_slices.py ./
            ln -s $scr/extract_atms.py   ./

            cp $exe ./

            echo $n > snapshot.inp

            if (($mu_id != 10)); then

                arg="4s/.*/"${mu[$mu_id-1]}"    # viewing angle mu/"
#                arg="4s/.*/"${mu[$mu_id-2]}"    # viewing angle mu/"

                sed -i '3s/.*/1      # rotation on or off (1 or 0)/' INPUT
                sed -i "$arg"                                        INPUT

            else

                sed -i '3s/.*/0      # rotation on or off (1 or 0)/' INPUT

            fi

            cd $pdir

        done

    done

    cd ..

done
